<?php
//NOMBRE
$NVEAUX=$_POST["NVEAUX"];
$NBOEUFS=$_POST["NBOEUFS"];
$NTAUREAUX=$_POST["NTAUREAUX"];
$NVACHES=$_POST["NVACHES"];
$NGENISSES=$_POST["NGENISSES"];
$NBELIERS=$_POST["NBELIERS"];
$NAGNEAUX=$_POST["NAGNEAUX"];
$NBREBIS=$_POST["NBREBIS"];
$NCHEVRES=$_POST["NCHEVRES"];
$NCHEVREAUX=$_POST["NCHEVREAUX"];
$NCHAMEAUX=$_POST["NCHAMEAUX"];
$NCHAMELLES=$_POST["NCHAMELLES"];
$NCHEVEAUX=$_POST["NCHEVEAUX"];
$NPOULINS=$_POST["NPOULINS"];
//VIANDE FORRAINE
$NFVEAUX=$_POST["NFVEAUX"];
$NFBOEUFS=$_POST["NFBOEUFS"];
$NFTAUREAUX=$_POST["NFTAUREAUX"];
$NFVACHES=$_POST["NFVACHES"];
$NFGENISSES=$_POST["NFGENISSES"];
$NFBELIERS=$_POST["NFBELIERS"];
$NFAGNEAUX=$_POST["NFAGNEAUX"];
$NFBREBIS=$_POST["NFBREBIS"];
$NFCHEVRES=$_POST["NFCHEVRES"];
$NFCHEVREAUX=$_POST["NFCHEVREAUX"];
$NFCHAMEAUX=$_POST["NFCHAMEAUX"];
$NFCHAMELLES=$_POST["NFCHAMELLES"];
$NFCHEVEAUX=$_POST["NFCHEVEAUX"];
$NFPOULINS=$_POST["NFPOULINS"];
//Saisies Totales
//Tuberculose:
$TVEAUX=$_POST["TVEAUX"];
$TBOEUFS=$_POST["TBOEUFS"];
$TTAUREAUX=$_POST["TTAUREAUX"];
$TVACHES=$_POST["TVACHES"];
$TGENISSES=$_POST["TGENISSES"];
$TBELIERS=$_POST["TBELIERS"];
$TAGNEAUX=$_POST["TAGNEAUX"];
$TBREBIS=$_POST["TBREBIS"];
$TCHEVRES=$_POST["TCHEVRES"];
$TCHEVREAUX=$_POST["TCHEVREAUX"];
$TCHAMEAUX=$_POST["TCHAMEAUX"];
$TCHAMELLES=$_POST["TCHAMELLES"];
$TCHEVEAUX=$_POST["TCHEVEAUX"];
$TPOULINS=$_POST["TPOULINS"];
//Viandes ictériques:
$IVEAUX=$_POST["IVEAUX"];
$IBOEUFS=$_POST["IBOEUFS"];
$ITAUREAUX=$_POST["ITAUREAUX"];
$IVACHES=$_POST["TVACHES"];
$IGENISSES=$_POST["TGENISSES"];
$TBELIERS=$_POST["TBELIERS"];
$TAGNEAUX=$_POST["TAGNEAUX"];
$TBREBIS=$_POST["TBREBIS"];
$TCHEVRES=$_POST["TCHEVRES"];
$TCHEVREAUX=$_POST["TCHEVREAUX"];
$TCHAMEAUX=$_POST["TCHAMEAUX"];
$TCHAMELLES=$_POST["TCHAMELLES"];
$TCHEVEAUX=$_POST["TCHEVEAUX"];
$TPOULINS=$_POST["TPOULINS"];
require('../TCPDF/battoire.php');
$pdf = new bat('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->SetDisplayMode('fullpage','single');//mode d affichage 
$pdf->AddPage();
$pdf->SetFont('aefurat', '', 12);
//************************CORPS*************************// 
$pdf->SALUBRITE($_POST["NBOUCHER"],$_POST["PBOUCHER"],$_POST["ADRESSE"]);
$pdf->AddPage();
$pdf->SAISIE($_POST["NBOUCHER"],$_POST["PBOUCHER"],$_POST["ADRESSE"]);
$pdf->Output();

?>
